AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dify-plugin-update-checker

  Sample SAM Template for dify-plugin-update-checker

Globals:
  Function:
    Timeout: 30

Resources:
  DifyPluginCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Environment:
        Variables:
          PLUGINS: "langgenius/openai,langgenius/anthropic,langgenius/gemini,langgenius/azure_openai,langgenius/cohere,langgenius/bedrock,langgenius/ollama"
          DISCORD_WEBHOOK_URL: ""
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Description: "1時間ごとにDifyプラグインの更新をチェック"
            Enabled: true

Outputs:
  DifyPluginCheckerFunction:
    Description: "Dify Plugin Checker Lambda Function ARN"
    Value: !GetAtt DifyPluginCheckerFunction.Arn
  DifyPluginCheckerFunctionIamRole:
    Description: "Implicit IAM Role created for Dify Plugin Checker function"
    Value: !GetAtt DifyPluginCheckerFunctionRole.Arn
